// GENERATED by ui/scripts/gen-kit-types.mjs — do not edit. Run `npm run gen:kit-types`.
//
// What a plugin's TypeScript needs from core: the kit's 64 globally registered
// components (DESIGN §37.5) and the `*.vue` module shim. Wired up by
// `"types": ["@core/ui/client"]` in @core/ui/tsconfig.plugin.json.

declare module 'vue' {
  export interface GlobalComponents {
    CoreAlert: typeof import('../../src/kit/components/CoreAlert.vue')['default']
    CoreAvatar: typeof import('../../src/kit/components/CoreAvatar.vue')['default']
    CoreBackground: typeof import('../../src/kit/components/CoreBackground.vue')['default']
    CoreBadge: typeof import('../../src/kit/components/CoreBadge.vue')['default']
    CoreBrand: typeof import('../../src/kit/components/CoreBrand.vue')['default']
    CoreButton: typeof import('../../src/kit/components/CoreButton.vue')['default']
    CoreCard: typeof import('../../src/kit/components/CoreCard.vue')['default']
    CoreCheckbox: typeof import('../../src/kit/components/CoreCheckbox.vue')['default']
    CoreChips: typeof import('../../src/kit/components/CoreChips.vue')['default']
    CoreCompass: typeof import('../../src/kit/components/CoreCompass.vue')['default']
    CoreContextMenu: typeof import('../../src/kit/components/CoreContextMenu.vue')['default']
    CoreDash: typeof import('../../src/kit/components/CoreDash.vue')['default']
    CoreDialog: typeof import('../../src/kit/components/CoreDialog.vue')['default']
    CoreDivider: typeof import('../../src/kit/components/CoreDivider.vue')['default']
    CoreDrawer: typeof import('../../src/kit/components/CoreDrawer.vue')['default']
    CoreEmpty: typeof import('../../src/kit/components/CoreEmpty.vue')['default']
    CoreField: typeof import('../../src/kit/components/CoreField.vue')['default']
    CoreHeading: typeof import('../../src/kit/components/CoreHeading.vue')['default']
    CoreHotbar: typeof import('../../src/kit/components/CoreHotbar.vue')['default']
    CoreHudTile: typeof import('../../src/kit/components/CoreHudTile.vue')['default']
    CoreIcon: typeof import('../../src/kit/components/CoreIcon.vue')['default']
    CoreIconButton: typeof import('../../src/kit/components/CoreIconButton.vue')['default']
    CoreInput: typeof import('../../src/kit/components/CoreInput.vue')['default']
    CoreInteractionDot: typeof import('../../src/kit/components/CoreInteractionDot.vue')['default']
    CoreKey: typeof import('../../src/kit/components/CoreKey.vue')['default']
    CoreKeyHint: typeof import('../../src/kit/components/CoreKeyHint.vue')['default']
    CoreKeyHints: typeof import('../../src/kit/components/CoreKeyHints.vue')['default']
    CoreKeyValue: typeof import('../../src/kit/components/CoreKeyValue.vue')['default']
    CoreList: typeof import('../../src/kit/components/CoreList.vue')['default']
    CoreListItem: typeof import('../../src/kit/components/CoreListItem.vue')['default']
    CoreMenu: typeof import('../../src/kit/components/CoreMenu.vue')['default']
    CoreNumberInput: typeof import('../../src/kit/components/CoreNumberInput.vue')['default']
    CoreObjective: typeof import('../../src/kit/components/CoreObjective.vue')['default']
    CorePanel: typeof import('../../src/kit/components/CorePanel.vue')['default']
    CorePlayerChip: typeof import('../../src/kit/components/CorePlayerChip.vue')['default']
    CorePopover: typeof import('../../src/kit/components/CorePopover.vue')['default']
    CoreProgress: typeof import('../../src/kit/components/CoreProgress.vue')['default']
    CorePrompt: typeof import('../../src/kit/components/CorePrompt.vue')['default']
    CorePromptGroup: typeof import('../../src/kit/components/CorePromptGroup.vue')['default']
    CoreRadio: typeof import('../../src/kit/components/CoreRadio.vue')['default']
    CoreRadioGroup: typeof import('../../src/kit/components/CoreRadioGroup.vue')['default']
    CoreRing: typeof import('../../src/kit/components/CoreRing.vue')['default']
    CoreScreen: typeof import('../../src/kit/components/CoreScreen.vue')['default']
    CoreSelect: typeof import('../../src/kit/components/CoreSelect.vue')['default']
    CoreShard: typeof import('../../src/kit/components/CoreShard.vue')['default']
    CoreSkeleton: typeof import('../../src/kit/components/CoreSkeleton.vue')['default']
    CoreSlider: typeof import('../../src/kit/components/CoreSlider.vue')['default']
    CoreSlot: typeof import('../../src/kit/components/CoreSlot.vue')['default']
    CoreSlotGrid: typeof import('../../src/kit/components/CoreSlotGrid.vue')['default']
    CoreSpinner: typeof import('../../src/kit/components/CoreSpinner.vue')['default']
    CoreStatBar: typeof import('../../src/kit/components/CoreStatBar.vue')['default']
    CoreStatRow: typeof import('../../src/kit/components/CoreStatRow.vue')['default']
    CoreStepper: typeof import('../../src/kit/components/CoreStepper.vue')['default']
    CoreSwatches: typeof import('../../src/kit/components/CoreSwatches.vue')['default']
    CoreSwitch: typeof import('../../src/kit/components/CoreSwitch.vue')['default']
    CoreTable: typeof import('../../src/kit/components/CoreTable.vue')['default']
    CoreTabs: typeof import('../../src/kit/components/CoreTabs.vue')['default']
    CoreTag: typeof import('../../src/kit/components/CoreTag.vue')['default']
    CoreTagline: typeof import('../../src/kit/components/CoreTagline.vue')['default']
    CoreTextarea: typeof import('../../src/kit/components/CoreTextarea.vue')['default']
    CoreToast: typeof import('../../src/kit/components/CoreToast.vue')['default']
    CoreTooltip: typeof import('../../src/kit/components/CoreTooltip.vue')['default']
    CoreTracker: typeof import('../../src/kit/components/CoreTracker.vue')['default']
    CoreVital: typeof import('../../src/kit/components/CoreVital.vue')['default']
  }
}

declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent<Record<string, unknown>, Record<string, unknown>, unknown>
  export default component
}

export {}
